//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lua_IDEA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lua_IDEA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function m155()\r\n    local XWidth = 70\r\n    local YWidth = 50\r\n    local SafeZ  = 3\r\n    local ProbeZ = -3\r\n    local StepX  = 15\r\n    local StepY  = 15\r\n    local Feed   = 50\r\n    local TipHeight = 0\r\n    local ProbeFilename = \&quot;C:\\\\temp\\\\probe.txt\&quot;\r\n     \r\n    PushCurrentDistanceMode()\r\n    PushCurrentMotionMode()\r\n     \r\n    if (IsProbingPinConfigured()) then\r\n        -- open the file\r\n        file, msg = io.open(ProbeFilename, \&quot;w\&quot;)\r\n         \r\n        if (file  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Macro_M155 {
            get {
                return ResourceManager.GetString("Macro_M155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function mxxx()
        ///	local outputs_count = 8
        ///                for i = 0, outputs_count  do 
        ///                    if (PinGetState(Outputs.UserOutput_0 + i)) then
        ///                        DisplayMessage(&quot;Output_&quot;..i..&quot; ON&quot;)
        ///                    else
        ///                        DisplayMessage(&quot;Output_&quot;..i..&quot; OFF&quot;)
        ///                    end
        ///                end
        ///end.
        /// </summary>
        internal static string Macro_MXXX {
            get {
                return ResourceManager.GetString("Macro_MXXX", resourceCulture);
            }
        }
    }
}
